site_name: VeadoSC
site_url: https://veadosc.kekemui.gg
repo_url: https://github.com/Kekemui/veadosc-docs
repo_name: veadosc-docs
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - For Users: for_users.md
  # - For Developers: 
  #   - developers/vt-websockets.md
theme:
  features:
    - search.highlight
    - search.suggest
  name: material
  palette:
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
plugins: 
  - search
  - offline
markdown_extensions:
  - def_list
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc
site_dir: build
extra:
  version:
    provider: mike
  social: 
    - icon: fontawesome/brands/github
      name: VeadoSC
      link: https://github.com/Kekemui